### ISSUE TITLE
Unable to parse request with USAA

### ISSUE THREAD

**Issue by jmgilman** [euforic/banking.js#33] opened 2016-01-22 21:44 UTC
```
var bank = Banking({
        fid: "24591",
        fidOrg: "USAA",
        url: "https://service2.usaa.com/ofx/OFXServlet",
        bankId: "",
        user: "",
        password: "",
        accId: "",
        accType: "CHECKING",
        ofxVer: "103",
        app: "QBKS",
        appVer: "1900"
});
```

Using the above configuration I am getting the following error:

> OFXAdapter: Failed to parse request: Unable to parse a composite field "OFXRequest.OFXRequest": postTag "/OFX" not found.
> Remaining unparsed data:

It then has a bunch of XML data with some private information in it (looks like my original configuration data).

**Comment by jmgilman** [comment] 2016-01-22 21:51
If I include USAA's routing number (314074269) I get the following error instead:

> FXAdapter: FFSException: OFXAdapter: Unable to find FI information. Make sure the FI in the request is configured with this server

**Comment by withinboredom** [comment] 2016-03-26 03:23
This might be due to #8 ... and the fact that the lib doesn't stick to header standards: https://www.w3.org/Protocols/rfc2616/rfc2616-sec2.html#sec2.2

**Comment by jmgilman** [comment] 2016-03-26 03:57
Yeah, I saw that bug and tried different delimiters but had no luck.

**Comment by withinboredom** [comment] 2016-03-26 04:00
I use usaa, let me dig in and see if I can get the same error

**Comment by withinboredom** [comment] 2016-03-26 04:20
Same exact error ...

**Comment by jmgilman** [comment] 2016-03-26 04:37
Yeah, I played around with the header quite a bit but could never get it to work. For some reason no matter how I structured the text it could never find the end tag.

**Comment by jdlewis92** [comment] 2016-06-07 05:24
> OFXAdapter: FFSException: OFXAdapter: Unable to find FI information. Make sure the FI in the request is configured with this server

I believe this is caused by 
> ofxVer: "103"

Try omitting that variable all together or setting it to "102"

**Comment by risacher** [comment] 2016-12-06 21:27
The following worked for me on 2016-12-06:

``` javascript
var bank = Banking({                                                                                   
    fid: 24591                                                                               
  , fidOrg: 'USAA'                           
  , url: 'https://service2.usaa.com/ofx/OFXServlet'
  , bankId: '314074269' /* If bank account use your bank routing number otherwise set to null */ 
  , user: '012345678' /* my USAA number, zero padded to 9 digits */                                            
  , password: '1234' /* my USAA pin */
  , accId: '0001234567' /* Account Number, zero padded to 10 digits */
  , accType: 'CHECKING' /* CHECKING || SAVINGS || MONEYMRKT || CREDITCARD */
  , ofxVer: 102 /* 103 DOES NOT WORK*/                         
  , app: 'QBKS' /* default  'QWIN' */                   
  , appVer: '1900' /* default 1700 */                                                                      
});
```

**Comment by euforic** [comment] 2016-12-06 21:56
Closing issue, but feel free to reopen if your still having trouble

**Closed by euforic** 2016-12-06 21:56 UTC
